---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.install_mongodb"
      tags:
        - "labocbz.install_mongodb"
      vars:
        install_mongodb__version: "{{ inv_install_mongodb__version }}"
        install_mongodb__distribution_release: "{{ inv_install_mongodb__distribution_release }}"
        install_mongodb__architecture: "{{ inv_install_mongodb__architecture }}"
        install_mongodb__db_user: "{{ inv_install_mongodb__db_user }}"
        install_mongodb__db_group: "{{ inv_install_mongodb__db_group }}"
        install_mongodb__db_path: "{{ inv_install_mongodb__db_path }}"
        install_mongodb__log_path: "{{ inv_install_mongodb__log_path }}"
        install_mongodb__log_file: "{{ inv_install_mongodb__log_file }}"
        install_mongodb__ssl_path: "{{ inv_install_mongodb__ssl_path }}"
        install_mongodb__bind: "{{ inv_install_mongodb__bind }}"
        install_mongodb__port: "{{ inv_install_mongodb__port }}"
        install_mongodb__ssl: "{{ inv_install_mongodb__ssl }}"
        install_mongodb__ssl_cert: "{{ inv_install_mongodb__ssl_cert }}"
        install_mongodb__ssl_key: "{{ inv_install_mongodb__ssl_key }}"
        install_mongodb__ssl_pem_key_file: "{{ inv_install_mongodb__ssl_pem_key_file }}"
        install_mongodb__ssl_client_auth: "{{ inv_install_mongodb__ssl_client_auth }}"
        install_mongodb__ssl_ca: "{{ inv_install_mongodb__ssl_ca }}"
        install_mongodb__admin_login: "{{ inv_install_mongodb__admin_login }}"
        install_mongodb__admin_password: "{{ inv_install_mongodb__admin_password }}"
        install_mongodb__ssl_ca_file: "{{ inv_install_mongodb__ssl_ca_file }}"
      ansible.builtin.include_role:
        name: "labocbz.install_mongodb"
