---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.prepare_host"
      tags:
        - "labocbz.prepare_host"
      vars:
        prepare_host___users: "{{ inv_prepare_host___users }}"
        prepare_host___packages_removed: "{{ inv_prepare_host___packages_removed }}"
        prepare_host___packages_installed: "{{ inv_prepare_host___packages_installed }}"
        prepare_host___system_users: "{{ inv_prepare_host___system_users }}"
      ansible.builtin.include_role:
        name: "labocbz.prepare_host"
