---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_mongodb"
      tags:
        - "labocbz.install_mongodb"
      vars:
        install_mongodb_version: "{{ inv_install_mongodb_version }}"
        install_mongodb_distribution_release: "{{ inv_install_mongodb_distribution_release }}"
        install_mongodb_architecture: "{{ inv_install_mongodb_architecture }}"
        install_mongodb_db_user: "{{ inv_install_mongodb_db_user }}"
        install_mongodb_db_group: "{{ inv_install_mongodb_db_group }}"
        install_mongodb_db_path: "{{ inv_install_mongodb_db_path }}"
        install_mongodb_log_path: "{{ inv_install_mongodb_log_path }}"
        install_mongodb_log_file: "{{ inv_install_mongodb_log_file }}"
        install_mongodb_ssl_path: "{{ inv_install_mongodb_ssl_path }}"
        install_mongodb_bind: "{{ inv_install_mongodb_bind }}"
        install_mongodb_port: "{{ inv_install_mongodb_port }}"
        install_mongodb_ssl: "{{ inv_install_mongodb_ssl }}"
        install_mongodb_ssl_cert: "{{ inv_install_mongodb_ssl_cert }}"
        install_mongodb_ssl_key: "{{ inv_install_mongodb_ssl_key }}"
        install_mongodb_ssl_pem_key_file: "{{ inv_install_mongodb_ssl_pem_key_file }}"
        install_mongodb_ssl_client_auth: "{{ inv_install_mongodb_ssl_client_auth }}"
        install_mongodb_ssl_ca: "{{ inv_install_mongodb_ssl_ca }}"
        install_mongodb_admin_login: "{{ inv_install_mongodb_admin_login }}"
        install_mongodb_admin_password: "{{ inv_install_mongodb_admin_password }}"
      ansible.builtin.include_role:
        name: "labocbz.install_mongodb"
